### ISSUE TITLE
why can't start download ?

### ISSUE THREAD

**Issue by p1020119** [SN4T14/capturebate-node#17]
Unhandled rejection Error: ConnectionTimeoutError: The connection timed out.
Code: 606
request: undefined
requestState: undefined
    at Object.ensureErrorObject (C:\capturebate-node-master\capturebate-node-master\node_modules\bluebird\js\main\util.js:261:20)
    at Promise._rejectCallback (C:\capturebate-node-master\capturebate-node-master\node_modules\bluebird\js\main\promise.js:472:22)
    at PromiseArray.__hardReject__.PromiseArray._reject (C:\capturebate-node-master\capturebate-node-master\node_modules\bluebird\js\main\promise_array.js:109:19)
    at Promise._settlePromiseAt (C:\capturebate-node-master\capturebate-node-master\node_modules\bluebird\js\main\promise.js:582:21)
    at Promise._settlePromises (C:\capturebate-node-master\capturebate-node-master\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\capturebate-node-master\capturebate-node-master\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\capturebate-node-master\capturebate-node-master\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\capturebate-node-master\capturebate-node-master\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)

**Comment by sstativa** [comment]
There were complains about broken login [#16](https://github.com/SN4T14/capturebate-node/issues/16). Might be your issue is a result of this.
